// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.2.2
// Project name: Test_Project

#ifndef UI_INDEXPAGE_H
#define UI_INDEXPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_indexpage
extern void ui_indexpage_screen_init(void);
extern void ui_indexpage_screen_destroy(void);
extern lv_obj_t * ui_indexpage;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

