// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.2.2
// Project name: Test_Project

#ifndef _TEST_PROJECT_UI_H
#define _TEST_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_indexpage.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1717730324);    // assets/WPS图片-修改尺寸.png

// FONTS
LV_FONT_DECLARE(ui_font_SiYuan32);
LV_FONT_DECLARE(ui_font_SiYuan16);
LV_FONT_DECLARE(ui_font_iconfont32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
