// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

extern const lv_font_t ui_font_iconfont28;
extern const lv_font_t ui_font_iconfont30;
extern const lv_font_t ui_font_iconfont32;
extern const lv_font_t ui_font_iconfont34;


///////////////////// SCREENS ////////////////////

#include "./screens/ui_HomePage.h"

///////////////////// VARIABLES ////////////////////

// UI INIT
void ui_init(void);
void ui_destroy(void);

// Runtime data interface. Call these from the LVGL task context.
void ui_set_sensor_values(const char * temperature, const char * humidity);
void ui_set_connection_state(const char * state);
void ui_set_ai_text(const char * text);
void ui_set_brightness(uint8_t percent);
void ui_handle_swipe(lv_dir_t direction);
void ui_handle_touch(lv_coord_t x, lv_coord_t y);
void ui_open_apps(void);
void ui_handle_key_confirm(void);
void ui_set_time_from_network(uint16_t year, uint8_t month, uint8_t day,
                              uint8_t hour, uint8_t minute, uint8_t second);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
